# Generated by Django 4.0.7 on 2022-08-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_cislo', models.CharField(max_length=9)),
                ('rod_cislo', models.CharField(max_length=20)),
                ('vek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poradce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('tel_cislo', models.CharField(max_length=9)),
                ('rod_cislo', models.CharField(max_length=20)),
                ('vek', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Smlouva',
            fields=[
                ('ev_cislo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('instituce', models.CharField(max_length=20)),
                ('dat_uzavreni', models.DateField()),
                ('dat_platnosti', models.DateField()),
                ('dat_ukonceni', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.klient')),
                ('spravce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.poradce')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
