# Generated by Django 4.0.7 on 2022-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_klient_poradce_smlouva_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poradce',
            name='vek',
            field=models.IntegerField(),
        ),
    ]
