# Generated by Django 4.0.7 on 2022-08-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_poradce_vek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('PIN', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('PIN', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('reg_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=20)),
                ('date_close', models.DateField()),
                ('date_valid', models.DateField()),
                ('date_end', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.advisor')),
            ],
        ),
        migrations.RemoveField(
            model_name='smlouva',
            name='klient',
        ),
        migrations.RemoveField(
            model_name='smlouva',
            name='spravce',
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
        migrations.DeleteModel(
            name='Poradce',
        ),
        migrations.DeleteModel(
            name='Smlouva',
        ),
    ]
